import './globals.css'
import { MoralisClientProvider } from '../components/MoralisClientProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <MoralisClientProvider>
      <html lang='en'>
        <body>{children}</body>
      </html>
    </MoralisClientProvider>
  )
}
